name: Regenerate PluginMaster

on:
  workflow_dispatch:
  push:
    paths: 
      - plugins/**

concurrency: regenerate

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate PluginMaster
        run: |
          node generate_pluginmaster.mjs

      - name: Commit PluginMaster
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Regenerate PluginMaster
